title: Sutisna Wahyu
logo: /assets/img/Tisna.png
description: Tech enthusiast, fast learner, and resilient professional with experience in IT support, engineering, and sales across multiple industries.
show_download: true
theme: jekyll-theme-minimal
